### ISSUE TITLE
cmake failed on ubuntu20.04

### ISSUE THREAD

**Issue by haoda-li** [psarahdactyl/computer-graphics-bounding-volume-hierarchy#1]
The error trace is 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:397 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libigl/cmake/libigl.cmake:321 (find_package)
  cmake/FindLIBIGL.cmake:36 (include)
  CMakeLists.txt:10 (find_package)

I'm sure that I've installed all the packages specified in the assignments.

**Comment by honglin-c** [comment]
Can you check the installation of OpenGL again, like `sudo apt install mesa-common-dev libgl1-mesa-dev`?

**Comment by honglin-c** [comment]
Sorry that I'm not a Linux user and I'm not quite sure about the OpenGL and cmake under Linux.

**Comment by haoda-li** [comment]
It seems that libigl cannot find OpenGL when I have both Nvidia OpenGL and Mesa installed. Anyway,I have switched to Windows and everything works fine on Windows.
