### ISSUE TITLE
Is the x y z value in min corner always smaller than the value in max corner?

### ISSUE THREAD

**Issue by QiiLin** [psarahdactyl/computer-graphics-bounding-volume-hierarchy#4]
Is the x y z value in min corner always smaller than the value in the max corner?

**Comment by honglin-c** [comment]
Yes. 
min_corner is the corner with the smallest x, y, z value of the bounding box, and max_corner is the corner with the largest x, y, z value of the bounding box. (You'll need to set min_corner and max_corner correctly in insert_triangle_into_box.cpp and insert_box_into_box.cpp.)

**Comment by QiiLin** [comment]
Since we are using center to do the partition, I wonder if it is enough to just use the center to find the longest axis?

**Comment by honglin-c** [comment]
If you can use the center to find the longest axis, that's fine. But I think you still need the max_corner and min_corner to find which axis is the longest.
