### ISSUE TITLE
Why the running time for  ./rays ..\data\rubber-ducky.obj is much lower than the one in the README?

### ISSUE THREAD

**Issue by QiiLin** [psarahdactyl/computer-graphics-bounding-volume-hierarchy#5]
I got the result below: 
# Ray Triangle Mesh Intersection
  |V| 2050
  |F| 4096

  Firing 1000 rays...

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   0.06717228889 |
  | build tree  |   0.00329661369 |
  | use tree    |   0.00153398514 |
The number of V and F also doesn't match.
I don't why it is slower than the one in the README...Is this going to be an issue?
By the way, It is running on Windows.

**Comment by honglin-c** [comment]
Oops, you'll need to run `./rays ../data/bob.obj 100` to get the result in the README. We'll fix the typo in the README. Thanks!

**Comment by QiiLin** [comment]
... Ok, now I got the following:

This is still slow.
I can't find where I did wrong here..... I first go through the objects to find the max_x min_x ....maxz, minz etc. Then, I compare the difference of each axis.... and find the longest axis.  From there I go through the objects and did the partition. The midpoint is the (max value of longest axis + min value of longest axis) * 0.5... I really don't know what I did wrong here.  Give you give me any hint?
# Ray Triangle Mesh Intersection
  |V| 334
  |F| 668

  Firing 1000 rays...

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   0.01112055779 |
  | build tree  |   0.00051093102 |
  | use tree    |   0.00081110001 |
Ok, my bad... I realized we want to do a BFS for the ray_intersect.. but still why the running time for the tree construction takes that long?

**Comment by honglin-c** [comment]
The timing for `use tree` seems to be a bit slower, maybe check `AABBTree_ray_intersect.cpp` ? Also in the README it's shooting 100 rays, so you may need to call `./rays ../data/bob.obj 100`.

**Comment by honglin-c** [comment]
It's a DFS for ray_intersect, see Section 12.3.4 of the textbook. BFS is for distance query in `point_AABBTree_squared_distance`.

**Comment by QiiLin** [comment]
My bad... I tried with 100... but I did recall that prof mentions about using BFS for ray_intersect.. but the current result is close to the one in README
# Ray Triangle Mesh Intersection
  |V| 334
  |F| 668

  Firing 100 rays...

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   0.00115799904 |
  | build tree  |   0.00049734116 |
  | use tree    |   0.00008153915 |
