### ISSUE TITLE
Is there any other reason for brute force to be that slow....?

### ISSUE THREAD

**Issue by QiiLin** [psarahdactyl/computer-graphics-bounding-volume-hierarchy#6]
I tried ./intersections ../data/knight.obj ../data/cheburashka.obj
I got the following.. It seems like the brute force is only using triangle_triangle_intersection function, but for that function, I basically just run 6 calls to the ray_intersect_triangle... It should not be that slow...What could be the reason? 
# Triangle Mesh Intersection Detection
  |VA| 2002
  |FA| 4000

  |VB| 6669
  |FB| 13334

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   7.13125395775 |
  | build trees |   0.01540732384 |
  | use trees   |   0.00452184677 |

**Comment by honglin-c** [comment]
You can try some general triangle-triangle intersection algorithms here: https://q.utoronto.ca/courses/159857/discussion_topics/674459

**Comment by wisemandenny** [comment]
> You can try some general triangle-triangle intersection algorithms here: https://q.utoronto.ca/courses/159857/discussion_topics/674459

this is the link inside the post linked above: https://stackoverflow.com/questions/7113344/find-whether-two-triangles-intersect-or-not
